### ISSUE TITLE
Safari Failing Tests

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-integration-tests#146]
We seem to not be able to get sucessful tests on Safari for different reasons for the last 6 runs.

Not sure why or its just underpowered VM's by GitHub Action...

cc @christophs78

**Comment by christophs78** [comment]
Probably this is due to a newer vm-version, which contains a newer safari.

Last working:
```
2021-05-04T06:38:14.0763750Z Environment: macos-10.15
2021-05-04T06:38:14.0764250Z Version: 20210423.1
2021-05-04T06:38:14.0765250Z Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210423.1/images/macos/macos-10.15-Readme.md
2021-05-04T06:38:14.0766690Z Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210423.1
```

Now:
```
2021-05-06T18:33:00.8822230Z Environment: macos-10.15
2021-05-06T18:33:00.8822860Z Version: 20210503.2
2021-05-06T18:33:00.8824010Z Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210503.2/images/macos/macos-10.15-Readme.md
2021-05-06T18:33:00.8825340Z Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210503.2
```

When we look into readme.md

Last working:
Safari 14.0.3 (15610.4.3.1.7)
SafariDriver 14.0.3 (15610.4.3.1.7)

Now:
Safari 14.1 (15611.1.21.161.5)
SafariDriver 14.1 (15611.1.21.161.5)

IMO this looks like a Safari / SafariDriver - regression.

**Comment by melloware** [comment]
Thank you for providing this.

**Comment by christophs78** [comment]
IMO it´s weird.
It can not be a VM performance issue because we use the same VMs for Chrome and Firefox too.
My currently best bet is a new stability-issue introduced with Safari 14.1

**Comment by christophs78** [comment]
Maybe we should restart safari each few tests.
https://stackoverflow.com/questions/50466575/restart-browser-between-tests/50467881
Not sure yet how to add this.

**Comment by melloware** [comment]
OK let me know what you find out.  I do hate how brittle and different Safari seems to be.

**Comment by christophs78** [comment]
Safari is kind of a "Diva". I´ll realy wish Apple would care more about this. It should not be a resource-thing an their side. Maybe a political thing because they prefer to sell App´s through their Appstore. Even their PWA-support is not where it should be.

We already do the browser-restart-"thing" as part of https://github.com/primefaces-extensions/primefaces-selenium/blob/master/primefaces-selenium-core/src/main/java/org/primefaces/extensions/selenium/internal/junit/WebDriverExtension.java#L41.
But more Safari - "fun": https://github.com/appium/appium/issues/9938

So i´ll try to add the 
```
driver.close();
sleep(1000);
driver.quit();
```
trick to PF selenium. (for Safari only)

**Comment by christophs78** [comment]
I´m running out of ideas. At some random point something happens with Safari 14.1 that breaks `PrimeSelenium.guardAjax`.
And probably driver.quit() does not really shut´s down Safari complete.
@melloware : Maybe you can play around with this some time later on your private MacOS-device.

**Comment by melloware** [comment]
Yep for now should we disable Safari tests from the build?

**Comment by christophs78** [comment]
Some notes.
Even Safari has new (Selenium) SessionID´s and window-handles for each integrationtest-class. But there must be something shared in background we can not look into when running on Github Actions.
After debugging into PF Selenium AjaxGuard it (still) looks like starting from random point X Safari can´t do XMLHttpRequest anymore. Whatever is going on with Safari.
Maybe we should just wait for some weeks and hope this issue disappears with another future Safari-(minor)-update.

**Comment by melloware** [comment]
Agreed I will leave this open for now.

**Comment by melloware** [comment]
So far this has been running great since you disabled Safari. :)
